INSERT INTO Answers(answer,Type,Question_ID) VALUES('odio a purus. Duis','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('ipsum ac','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('per conubia','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('imperdiet dictum magna. Ut','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('ligula. Donec luctus aliquet odio. Etiam ligula tortor,','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('dictum eu, placerat eget,','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('pede, nonummy','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('vel, mauris. Integer sem elit, pharetra ut, pharetra sed,','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('elit. Curabitur sed tortor. Integer aliquam adipiscing','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('felis, adipiscing fringilla, porttitor vulputate, posuere','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('lectus pede, ultrices','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('non leo. Vivamus','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('aliquet magna a','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('sapien. Nunc pulvinar','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('a, enim. Suspendisse aliquet, sem','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('accumsan neque et nunc. Quisque ornare tortor at','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('tellus, imperdiet non, vestibulum','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('bibendum sed, est. Nunc laoreet lectus quis massa.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('eget ipsum. Suspendisse','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('at augue id ante dictum cursus. Nunc mauris elit,','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('magna. Lorem','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('arcu ac orci. Ut','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('primis in faucibus orci luctus et ultrices posuere cubilia','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('tellus','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('sem, vitae aliquam eros turpis non enim.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('pede nec ante blandit viverra.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('dui. Fusce diam','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('molestie','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('Sed eu eros.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('arcu. Aliquam ultrices iaculis odio.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('placerat eget,','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('orci, in consequat enim diam vel arcu.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('sagittis. Nullam vitae diam. Proin dolor.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('nonummy ultricies ornare, elit elit fermentum','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('ut','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('tellus lorem eu metus. In lorem. Donec elementum,','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('purus. Duis elementum, dui quis accumsan convallis,','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('lectus rutrum urna, nec luctus felis purus','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('pretium et, rutrum non, hendrerit','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('amet nulla. Donec non justo. Proin','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('nisi sem semper erat, in consectetuer ipsum nunc id enim.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('sed turpis nec mauris blandit mattis. Cras eget nisi dictum','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('felis ullamcorper viverra. Maecenas','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('dui. Cras pellentesque. Sed','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('turpis. Nulla aliquet. Proin velit. Sed','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('Class aptent taciti sociosqu ad','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('orci lacus vestibulum lorem, sit amet ultricies','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('nec metus facilisis lorem tristique aliquet. Phasellus','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('feugiat placerat velit. Quisque varius.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('tellus justo sit amet nulla. Donec non','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('velit eu sem. Pellentesque ut','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('malesuada augue ut lacus. Nulla tincidunt, neque vitae','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('ac metus','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('non, hendrerit id, ante. Nunc mauris sapien, cursus','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('at, nisi. Cum sociis natoque penatibus et magnis dis parturient','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('turpis egestas. Fusce','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('lacus. Etiam bibendum fermentum metus. Aenean','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('augue ac ipsum. Phasellus vitae mauris sit amet lorem semper','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('in lobortis tellus','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('Nunc','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('Nulla facilisi. Sed neque. Sed eget lacus. Mauris','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('nascetur ridiculus','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('vitae, erat.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('feugiat. Sed nec metus facilisis lorem','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('risus','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('eu augue porttitor interdum. Sed','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('ridiculus','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('urna. Nunc quis arcu vel quam dignissim pharetra. Nam','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('sem, consequat nec, mollis vitae, posuere at, velit.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('nostra, per inceptos hymenaeos. Mauris ut quam','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('Nulla tincidunt, neque vitae semper egestas, urna justo','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('gravida mauris ut mi.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('mollis vitae, posuere at, velit. Cras lorem','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('ac urna. Ut tincidunt vehicula risus. Nulla','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('dolor sit amet, consectetuer adipiscing','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('interdum. Sed auctor odio a purus. Duis elementum,','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('eu, ligula. Aenean euismod mauris eu','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('cubilia Curae; Donec tincidunt.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('libero est, congue a, aliquet vel, vulputate','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('ullamcorper, velit','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('tristique pellentesque, tellus sem mollis dui, in sodales elit erat','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('dolor. Fusce','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('libero est, congue a,','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('libero at auctor ullamcorper, nisl arcu iaculis','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('ultricies','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('sem','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('eleifend. Cras sed leo. Cras','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('Curabitur vel','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('dui.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('massa. Quisque porttitor eros nec tellus.','SI, NO','1');
INSERT INTO Answers(answer,Type,Question_ID) VALUES('sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos.','SI, NO','1');
