INSERT INTO [dbo].[Questions] ([question]) VALUES (N'El resultado de multiplicar 25*25 es...')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'Piensa en el número 125, divídelo entre 5, vuélvelo a dividir por 5, y vuélvelo a dividir por 5. ¿Cuál es el resultado?')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'Piensa en el número 456, multiplícalo por 4, divídelo entre 6, y réstale 35. ¿Cuál es es resultado?')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'El resultado de dividir 8500 entre 5 es...')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'El 6 por ciento de 3500 es ...')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'Eleva 300 al cuadrado. El resultado es...')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'El 15 por ciento de 8000 es ...')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'Realiza la siguiente operación: 5+16+23+90-100+135')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'Calcula el 35% de 1000')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'El número resultante de elevar 6 al cubo es ...')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'El número resultante de elevar 16 al cuadrado es ...')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'Realiza la siguiente operación: (9/3)+(5+16)+(3+2)+(80/5)')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'NULLRealiza la siguiente operación: 5 + -51 + 31 + -3')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'Partiendo del número 1000, ¿Cuántas veces puedes dividir entre 8, siempre teniendo como resultado un entero?')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'Descuenta el 20 por ciento a 4000, el resultado es...')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'El 99 por cien de 2000 es ...')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'Realiza la siguiente operación: (5+6)+(3+9)-(5+5)')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'Descuenta el 40 por ciento a 8000, el resultado es...')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'El 5 por mil de 800 es ...')
INSERT INTO [dbo].[Questions] ([question]) VALUES (N'Partiendo del número 500, ¿Cuántas veces puedes dividir entre 5, siempre teniendo como resultado un entero?')
GO

